# Docker/prometheus.yml
global:
  scrape_interval: 15s   # scrape every 15 seconds
  evaluation_interval: 15s

scrape_configs:
  # 1) Scrape your FastAPI inference service
  - job_name: 'taxi_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['fastapi_server:8000']

  # 2) Scrape Prometheus’s own metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
